import { describe, it, expect } from 'vitest';
import { renderStorybookDecorator } from '../src/codegen/storybook-decorator.js';

describe('renderStorybookDecorator', () => {
  it('imports SitecoreProvider from the configured package', () => {
    const out = renderStorybookDecorator('@acme/sdk');
    expect(out).toContain("import { SitecoreProvider } from '@acme/sdk';");
    expect(out).not.toContain('@sitecore-content-sdk/nextjs');
  });

  it('exports a withSitecore decorator factory with a non-editing page', () => {
    const out = renderStorybookDecorator('@sitecore-content-sdk/nextjs');
    expect(out).toContain('export function withSitecore(');
    expect(out).toContain('isEditing: false');
    expect(out).toContain('componentMap');
    expect(out).toContain('<Story />');
    // Generated stories call withSitecore() with no args for leaf components —
    // the default parameter is load-bearing for that contract.
    expect(out).toContain('components: Record<string, ComponentType<any>> = {}');
  });

  it('tells the reader the file is generated once and safe to edit', () => {
    const out = renderStorybookDecorator('@sitecore-content-sdk/nextjs');
    expect(out).toContain('Generated by headcore');
    expect(out).toContain('only when missing');
  });
});
