/** A single-quoted TS string literal with backslashes and quotes escaped. */
function lit(s: string): string {
  return `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

export function renderDictionaryFile(keys: string[]): string {
  const entries = keys.map((k) => `  ${lit(k)}: ${lit(k)},`).join('\n');
  const body = entries ? `\n${entries}\n` : '';
  return `// AUTO-GENERATED by sitecore-scaffold. Do not edit.
export const dictionaryKeys = {${body}} as const;

export type DictionaryKey = keyof typeof dictionaryKeys;
`;
}
