/**
 * The shared Storybook decorator template. Emitted into the user's project at
 * `storybook.decoratorPath` only when the file doesn't exist yet — it belongs
 * to the user afterwards (they may need to adapt the page shape to their SDK
 * version, which this repo cannot compile against).
 */
export function renderStorybookDecorator(sitecorePackage: string): string {
  return `/* eslint-disable @typescript-eslint/no-explicit-any */
// Generated by headcore — shared Storybook decorator for Sitecore components.
// Wraps stories in the Content SDK provider so useSitecore() and <Placeholder>
// resolve outside a Sitecore-rendered page. headcore writes this file only when missing,
// so it is yours to edit (e.g. adjust the page shape to your SDK version).
import type { ComponentType, ReactElement } from 'react';
import { SitecoreProvider } from '${sitecorePackage}';

// Minimal page object: stories always render in normal (non-editing) mode.
const storybookPage: any = {
  mode: { isEditing: false, isPreview: false, isNormal: true },
  layout: { sitecore: { context: {}, route: null } },
};

/**
 * Decorator factory. Pass the components your story's placeholders must
 * resolve, e.g. \`decorators: [withSitecore({ CarouselSlide })]\`.
 */
export function withSitecore(components: Record<string, ComponentType<any>> = {}) {
  const componentMap: any = new Map(Object.entries(components));
  return function SitecoreStoryDecorator(Story: ComponentType): ReactElement {
    return (
      <SitecoreProvider api={{} as any} componentMap={componentMap} page={storybookPage}>
        <Story />
      </SitecoreProvider>
    );
  };
}
`;
}
